# Generated by Django 5.1.2 on 2024-11-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_blog', '0004_remove_comment_user_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Anonymous User', max_length=100),
        ),
    ]
